[package]
name = "multimixer-128"
version = "0.1.0"
edition = "2021"

[dependencies]
digest = "=0.11.0-pre.8"

[dev-dependencies]
digest = { version = "=0.11.0-pre.8", features = ["dev"] }
hex-literal = "0.4.1"
